const REACT_APP_API_URL = process.env.REACT_APP_API_URL;

const AUTH_ROUTE = "/auth";
const USER_ROUTE = "/users";
const MEALS_ROUTE = "/meals";
const MEALS_CATEGORIES_ROUTE = `${MEALS_ROUTE}/categories`;
const PRODUCTS_ROUTE = "/products";
const PRODUCTS_CATEGORIES_ROUTE = `${PRODUCTS_ROUTE}/categories`;
const DIETS_ROUTE = "/diets";

export {
  REACT_APP_API_URL,
  AUTH_ROUTE,
  USER_ROUTE,
  MEALS_ROUTE,
  MEALS_CATEGORIES_ROUTE,
  PRODUCTS_ROUTE,
  PRODUCTS_CATEGORIES_ROUTE,
  DIETS_ROUTE
};
